name: Deploy Flask OTP App to Azure

on:
  push:
    branches:
      - main  # or your default branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set working directory
        run: cd otp-login-app

      - name: Install dependencies
        run: |
          cd otp-login-app
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Zip the app
        run: |
          cd otp-login-app
          zip -r ../flask-app.zip . -x '*.git*'

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: test-app13
          slot-name: production
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
          package: flask-app.zip
