name: Deploy Flask OTP App to Azure

on:
  push:
    branches:
      - main  # Or replace with your default branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'  # Match Azure's runtime if needed

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Zip Application
        run: |
          zip -r app.zip . -x ".git/*"

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: test-app13  # Your Azure Web App name
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
          package: app.zip
