name: Deploy Flask OTP App to Azure

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          cd loginpage/otp-login-app
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Zip the app (without top folder)
        run: |
          cd loginpage/otp-login-app
          zip -r ../../flask-app.zip * .[^.]*

      - name: Deploy using Oryx Build
        uses: azure/webapps-deploy@v2
        with:
          app-name: test-app13
          slot-name: production
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
          package: flask-app.zip  # ✅ now correct
